name: mybrigitte

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    image: mybrigitte-backend:local
    ports:
      - "3001:3001"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    image: mybrigitte-web:local
    ports:
      - "8081:80"
