FROM oven/bun:1.4.2 AS builder
WORKDIR /app
COPY package.json bun.lock ./
RUN bun ci
COPY . .
RUN bun --bun run build

FROM nginx:stable-alpine AS runtime
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
